### PR TITLE
Feature/database

### PR DESCRIPTION
**Pull request by hkittylover**
fixed the count bug

### CODE REVIEW

**Comment by hkittylover** [comment]
connected the database to org specific

same issue with dashboard in which there is no info showing the extra details

Can't show the org name and its statistics and I dont know why.... NEED HELP ON THIS!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! naka JSON na yung data, same format with the json in org list

**Comment by hkittylover** [comment]
fixed na pala yung showing of org details

**Comment by hkittylover** [comment]
removed pycache cuz it is ruining my project...

need to remove it from the repo para next time magpupush tayo with pycache, maiignore yung pycache

**Comment by mjarenyap** [comment]
alright! will remove it from all branches

**Pull request merged**
